### ISSUE TITLE
[Bug]: Game crash with SCRN mod.

### ISSUE THREAD

**Issue by chronofox7685** [InsultingPros/KF2HUD#9]
### What happened?

After kill all zeds on the first round, at the moment of show the trader's path, the game crashes. The game show me this error:

 Build UT2004_Build_[2004-11-11_10.48]

OS: Windows NT 6.2 (Build: 9200)
CPU: GenuineIntel PentiumPro-class processor @ 2901 MHz with 3964MB RAM
Video: Intel(R) G41 Express Chipset (2104)

General protection fault!

History: UObject::execClassContext <- (KF2HUD KF-BioticsLab.KF2HUD @ Function KF2HUD.KF2HUD.DrawPortraitSE : 046B) <- UObject::ProcessEvent <- (KF2HUD KF-BioticsLab.KF2HUD, Function KFmod.HUDKillingFloor.PostRender) <- FPlayerSceneNode::Render <- UGameEngine::Draw <- UWindowsViewport::Repaint <- UWindowsClient::Tick <- ClientTick <- UGameEngine::Tick <- Level KF-BioticsLab <- UpdateWorld <- MainLoop <- FMallocWindows::Free <- FMallocWindows::Realloc <- 726F6F6C 0 FArray <- FArray::Realloc <- 0*2 <- FMallocWindows::Free

![Sin título](https://github.com/user-attachments/assets/e6835e40-0d2d-441c-9a64-6abe54969849)

**Comment by ArionDeath** [comment]
Hello, fixed this problem? I have same problem

**Comment by Shtoyan** [comment]
Hi. Please specify your Scrn packages versions.

If you have the latest ones (9.70.18) - try this release:
https://github.com/InsultingPros/KF2HUD/releases/tag/1.0.4

**Comment by Shtoyan** [comment]
Hi. Please specify your Scrn packages versions.

Anyway I recompiled against latest 9.70.18, you can also try it:
https://github.com/InsultingPros/KF2HUD/releases/tag/1.0.4

**Comment by ArionDeath** [comment]
ScrN Brutal KF Bundle v9. If i right understand from description its include all last versions of ScrN mods.

And for HUD work i need install that too, right?
[Server Perks]
[Scrn Shared]
[Scrn Balance]

Cuz in description of Bundle that:
ScrN Server Veterancy Handler v9.70
ScrN Shared Lib v9.70
ScrN Balance v9.70.18

**Comment by Shtoyan** [comment]
I double checked with those versions installed + the release I posted, and everything is fine on my side.

**Comment by ArionDeath** [comment]
One moment. I use it on client side. Not server. Work on both, right?

**Comment by ArionDeath** [comment]
WORK!!! WORK WORK WORK!!!! THANKS!!!

**Comment by Shtoyan** [comment]
Enjoy.
